# Generated by Django 3.2.17 on 2023-02-02 23:45

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('impression', 'impression'), ('engagement', 'engagement')], default='impression', max_length=50)),
                ('domain', models.CharField(max_length=250)),
                ('parameter', models.CharField(max_length=250)),
            ],
        ),
    ]
